---
version: "3.4"

services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      SPAN_STORAGE_TYPE: memory
    ports:
      - 6831:6831/udp
      - 16686:16686

